site_name: SQLMesh
repo_url: https://github.com/TobikoData/sqlmesh
repo_name: TobikoData/sqlmesh
nav:
  - "Overview": index.md
  - Get started:
    - prerequisites.md
    - installation.md
    - Quick Start:
      - quick_start.md
      - quickstart/cli.md
      - quickstart/notebook.md
      - quickstart/ui.md
  - Guides:
    - Project structure:
      - guides/projects.md
      - guides/multi_repo.md
    - Project setup:
      - guides/configuration.md
      - guides/connections.md
      - guides/scheduling.md
      - guides/notifications.md
      - guides/migrations.md
    - Project content:
      - guides/models.md
      - guides/incremental_time.md
      - guides/testing.md
    - SQLMesh tools:
      - guides/tablediff.md
  - Concepts:
    - concepts/overview.md
    - Development:
      - concepts/plans.md
      - concepts/environments.md
      - concepts/tests.md
      - concepts/audits.md
    - Models:
      - concepts/models/overview.md
      - concepts/models/model_kinds.md
      - concepts/models/sql_models.md
      - concepts/models/python_models.md
      - concepts/models/seed_models.md
      - concepts/models/external_models.md
    - Macros:
      - concepts/macros/overview.md
      - concepts/macros/macro_variables.md
      - concepts/macros/sqlmesh_macros.md
      - concepts/macros/jinja_macros.md
    - Metrics:
      - concepts/metrics/overview.md
      - concepts/metrics/definition.md
    - Architecture:
      - concepts/architecture/snapshots.md
      - concepts/architecture/serialization.md
    - concepts/glossary.md
  - Reference:
    - API:
      - reference/overview.md
      - reference/cli.md
      - reference/notebook.md
      - reference/python.md
    - Configuration:
      - reference/configuration.md
      - reference/model_configuration.md
  - Integrations:
    - "Overview": integrations/overview.md
    - Tools:
      - integrations/airflow.md
      - integrations/dbt.md
      - integrations/github.md
    - Execution engines:
      - integrations/engines/bigquery.md
      - integrations/engines/databricks.md
      - integrations/engines/duckdb.md
      - integrations/engines/mysql.md
      - integrations/engines/mssql.md
      - integrations/engines/postgres.md
      - integrations/engines/gcp-postgres.md
      - integrations/engines/redshift.md
      - integrations/engines/snowflake.md
      - integrations/engines/spark.md
  - Resources:
    - comparisons.md
    - development.md
  - "FAQ": faq/faq.md
  - API: _readthedocs/html/sqlmesh.html
theme:
  name: material
  logo: sqlmesh.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: #091c79
      accent: #cce8fe
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #cce8fe
      accent: #091c79
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
plugins:
  - include-markdown
  - search
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/extra.css
copyright: Tobiko Data Inc.
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://tobikodata.com/slack
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@tobikodata.com
    - icon: fontawesome/brands/github
      link: https://github.com/TobikoData/sqlmesh/issues/new
