site_name: SQLMesh
nav:
  - Overview:
    - "What is SQLMesh?": index.md
    - "SQLMesh advantages": why_sqlmesh.md
  - Get started:
    - Quick start:
      - quick_start.md
      - prerequisites.md
  - Guides:
    - guides/projects.md
    - guides/models.md
    - guides/testing.md
    - guides/scheduling.md
  - Concepts:
    - concepts/overview.md
    - Models:
      - concepts/models/overview.md
      - concepts/models/model_kinds.md
      - concepts/models/sql_models.md
      - concepts/models/python_models.md
      - concepts/models/seed_models.md
    - concepts/plans.md
    - concepts/environments.md
    - concepts/tests.md
    - concepts/audits.md
    - concepts/macros.md
    - concepts/hooks.md
    - concepts/team_development.md
    - Architecture:
      - concepts/architecture/snapshots.md
      - concepts/architecture/serialization.md
    - concepts/glossary.md
  - Reference:
    - API:
      - reference/overview.md
      - reference/cli.md
      - reference/notebook.md
      - reference/python.md
    - reference/configuration.md
  - Integrations:
    - integrations/overview.md
    - integrations/airflow.md
    - integrations/dbt.md
    - integrations/github.md
  - Best practices:
    - best_practices/recommended_workflow.md
  - Resources:
    - release_notes.md
    - community.md
    - development.md
theme:
  name: material
  logo: sqlmesh.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
plugins:
  - include-markdown
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Tobiko Data Inc.
