project: repo_1

gateways:
  local:
    connection:
      type: duckdb
      database: db.db

  memory:
    connection:
      type: duckdb

default_gateway: local

model_defaults:
  dialect: 'duckdb'
