version: "3.9"
name: tobiko-development
services:
  app:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: tobiko-app
    image: image-tobiko-app
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    volumes:
      - ./client/src:/app/src
    networks:
      - tobiko-development
    depends_on:
      - api

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: tobiko-api
    image: image-tobiko-api
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./server/api:/api/api
      - ../example:/api/example
    networks:
      - tobiko-development      

networks:
  tobiko-development:
    driver: bridge